import React, { useEffect } from 'react'
import style from '@/styles/Home.module.css'
import Footer from './components/Footer'
import Head from 'next/head'
import Image from 'next/image'


// Images
import about_1 from '../public/images/About/about_1.jpg'
import about_2 from '../public/images/About/about_2.jpg'
import about_3 from '../public/images/About/about_3.jpg'

export default function About() {

    useEffect(() => {
        // define a custom handler function
        // for the contextmenu event
        const handleContextMenu = (e) => {
            // prevent the right-click menu from appearing
            e.preventDefault()
        }

        // attach the event listener to 
        // the document object
        document.addEventListener("contextmenu", handleContextMenu)

        // clean up the event listener when 
        // the component unmounts
        return () => {
            document.removeEventListener("contextmenu", handleContextMenu)
        }
    }, [])

    return (
        <>
            <Head>
                <title>Sobre Ella</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>


            <div className={`${style.top_section} ${style.pd_top_56px}`}>
                <div className={`${style.container_default} ${style.position_relative___z_index_1} ${style.w_container}`}>
                    <div className={`${style.text_center} ${style.mg_bottom_40px}`}>
                        <div
                            className={`${style.inner_container} ${style._966px} ${style.center}`}
                        >
                            <h1 className={`${style.display_2} ${style.mg_bottom_0} ${style.about_title}`}>
                                Titulo Titulo Titulo Titulo
                            </h1>
                        </div>
                        <div
                            className={`${style.inner_container} ${style._686px} ${style.center}`}
                        >
                            <p className={style.mg_bottom_0}>
                                Dolor non massa ac rhoncus diam turpis consequat vitae velit orci nec
                                sit ut faucibus tristique facilisi accumsan proin dignissim
                                condimentum.
                            </p>
                        </div>
                    </div>
                    <Image
                        style={{ opacity: 1 }}
                        src={about_1}
                        // width={1244}
                        // height={777.5}
                        alt="How to design a simple, yet unique and memorable brand identity"
                        sizes="(max-width: 479px) 93vw, (max-width: 1439px) 95vw, 1244px"
                        className={`${style.border_radius_28px} ${style.width_100} ${style.image_about}`}
                        // quality={1}
                        placeholder='blur'
                    />
                </div>
                <div className={`${style.bg_secondary_5} ${style.bottom_30}`} />
            </div>


            {/* Content */}
            <div className={`${style.section} ${style.pd_top_100px} ${style.pd_bottom_140px}`}>
                <div className={`${style.container_default} ${style.w_container}`}>
                    <div id={style['content']} className={`${style.grid_2_columns} ${style._2_06fr___1fr}`}>
                        <div id={style["w-node-cc0e8660-fe4b-33ae-2877-9f8cf24f760f-b08c02c3"]}>
                            <div
                                style={{ opacity: 1 }}
                                className={`${style.rich_text} ${style.mg_bottom_56px} ${style.w_richtext}`}
                            >
                                <h2>Titulo Titulo</h2>
                                <p>
                                    Sed viverra ipsum nunc aliquet bibendum enim facilisis gravida. Diam
                                    phasellus vestibulum lorem sed risus ultricies. Magna sit amet purus
                                    gravida quis blandit. Arcu cursus vitae congue mauris. Nunc mattis
                                    enim ut tellus elementum sagittis vitae et leo. Semper risus in
                                    hendrerit gravida rutrum quisque non. At urna condimentum mattis
                                    pellentesque id nibh tortor. A erat nam at lectus urna duis
                                    convallis convallis tellus. Sit amet mauris commodo quis imperdiet
                                    massa. Vitae congue eu consequat ac felis.
                                </p>
                                <ul role="list">
                                    <li>
                                        Lorem ipsum dolor sit amet consectetur hendrerit gravida rutrum.
                                    </li>
                                    <li>A erat nam at lectus urna duis convallis convallis tellus.</li>
                                    <li>
                                        Arcu cursus vitae congue mauris mattis enim ut tellus elementum
                                        sagittis vitae et leo.
                                    </li>
                                    <li>
                                        Magna sit amet purus gravida quis blandit cursus congue mauris
                                        mattis enim.
                                    </li>
                                </ul>
                                <h3>Titulo Titulo</h3>
                                <p>
                                    Vestibulum lorem sed risus ultricies. Magna sit amet purus gravida
                                    quis blandit. Arcu cursus vitae congue mauris. Nunc mattis enim ut
                                    tellus elementum sagittis vitae et leo. Semper risus in hendrerit
                                    gravida rutrum quisque non.
                                </p>
                                <figure className={`${style.w_richtext_align_center} ${style.w_richtext_figure_type_image}`}>
                                    <div>
                                        <Image
                                            src={about_3}
                                            loading="lazy"
                                            alt=""
                                            className={`${style.border_radius_28px} ${style.image_about}`}
                                            disable
                                        />
                                    </div>
                                    <figcaption>
                                        Vitae congue mauris mattis enim ut tellus elementum sagittis vitae
                                        et leo.
                                    </figcaption>
                                </figure>
                                <h1>Titulo Titulo</h1>
                                <p>
                                    Eget aliquet nibh praesent tristique magna sit amet purus. Consequat
                                    id porta nibh venenatis cras sed felis. Nisl rhoncus mattis rhoncus
                                    urna neque viverra justo nec. Habitant morbi tristique senectus et
                                    netus et malesuada fames ac. Et tortor consequat id porta nibh
                                    venenatis cras sed felis. Fringilla est ullamcorper eget nulla
                                    facilisi. Mi sit amet mauris commodo quis. Eget arcu dictum varius
                                    duis at consectetur lorem.Venenatis cras sed felis eget velit
                                </p>
                                <ol start="" role="list">
                                    <li>Magna eget est lorem ipsum dolor.</li>
                                    <li>
                                        Enim lobortis scelerisque fermentum dui. Fringilla ut morbi
                                        tincidunt augue.
                                    </li>
                                    <li>Nascetur ridiculus mus mauris vitae.</li>
                                    <li>
                                        Egestas sed tempus urna et pharetra pharetra massa massa
                                        ultricies.
                                    </li>
                                </ol>
                                <h2>Titulo Titulo</h2>
                                <p>
                                    Mattis molestie a iaculis at. Volutpat est velit egestas dui id.
                                    Suspendisse potenti nullam ac tortor vitae purus faucibus. Aliquet
                                    nibh praesent tristique magna sit amet purus gravida. Volutpat
                                    blandit aliquam etiam erat velit scelerisque in dictum. Potenti
                                    nullam ac tortor vitae purus faucibus ornare suspendisse sed.
                                    Aliquet bibendum enim facilisis gravida neque convallis. Malesuada
                                    nunc vel risus commodo viverra maecenas. Varius sit amet mattis
                                    vulputate enim.
                                </p>
                                <blockquote>
                                    “Arcu cursus vitae congue mauris mattis enim ut tellus elementum
                                    sagittis vitae et leo nullam ac tortor”
                                </blockquote>
                            </div>
                        </div>
                        <div
                            id={style["w-node-_52a14746-332c-be19-a1ce-5b3d9f2487c3-b08c02c3"]}
                            className={`${style.card} ${style.newsletter_sticky_card}`}
                        >
                            <div className={style.mg_bottom_32px}>
                                <Image
                                    style={{ opacity: 1 }}
                                    src={about_2}
                                    width={306}
                                    height={451.76}
                                    alt="How to design a simple, yet unique and memorable brand identity"
                                    sizes="(max-width: 479px) 93vw, (max-width: 1439px) 95vw, 1244px"
                                    className={`${style.border_radius_28px} ${style.width_100} ${style.image_about} ${style.max_w_40px}`}
                                />
                            </div>
                            <h3 className={style.color_neutral_100}>Titulo</h3>
                            <p>
                                Vestibulum lorem sed risus ultricie magna sit amet purus gravida quis
                                blandit Arcu cursus.
                            </p>
                            <div className={`${style.bg_dot} ${style.newsletter_card___top_right_dot}`} />
                            <div className={`${style.bg_dot} ${style.newsletter_card___middle_right_dot}`} />
                            <div className={`${style.bg_dot} ${style.newsletter_card___bottom_left_dot}`} />
                        </div>

                    </div>
                </div>
            </div>

            <Footer />

        </>
    )
}
