import Head from 'next/head'
import { useEffect } from 'react';
import Link from 'next/link';
import Image from 'next/image'
import style from '@/styles/Home.module.css'
import Footer from './components/Footer'

import { gsap } from "gsap";
import { ScrollTrigger } from "gsap/dist/ScrollTrigger";

import { Swiper, SwiperSlide } from "swiper/react";
import { Autoplay, Pagination, Navigation, EffectCreative } from "swiper";

// Import Swiper styles
import "swiper/css";
import "swiper/css/pagination";
import "swiper/css/navigation";



import home_1 from '../public/images/Home/home_1.png'
import home_2 from '../public/images/Home/home_2.jpg'
import home_3 from '../public/images/Home/home_3.jpg'
import home_4 from '../public/images/Home/home_4.jpg'
import home_5 from '../public/images/Home/home_5.jpg'
import gallery_1 from '../public/images/Home/gallery_1.jpg'
import gallery_2 from '../public/images/Home/gallery_2.jpg'
import gallery_3 from '../public/images/Home/gallery_3.jpg'
import gallery_4 from '../public/images/Home/gallery_4.jpg'
import gallery_5 from '../public/images/Home/gallery_5.jpg'
import gallery_6 from '../public/images/Home/gallery_6.jpg'
import mark_testi from '../public/images/Home/mark_testi.png'
import blob from '../public/images/Home/blob.svg'
import text from '../public/images/Home/text.svg'
import shape2 from '../public/images/Home/shape2.svg'




export default function Home() {

  gsap.registerPlugin(ScrollTrigger);

  useEffect(() => {

    gsap.to(".grid_thirds_1", {
      y: -600,
      duration: 2,
      ease: 'none',
      scrollTrigger: {
        start: "+=1120",
        // trigger: ".grid_thirds_3",
        toggleActions: "restart pause reverse pause",
        end: 'bottom',
        scrub: 1,
      }
    }
    );

    gsap.to(".grid_thirds_2", {
      y: 600,
      duration: 2,
      ease: 'none',
      scrollTrigger: {
        start: "+=1420",
        // trigger: ".grid_thirds_1",
        toggleActions: "restart pause reverse pause",
        end: 'bottom',
        scrub: 1,
      }
    }
    );


    let mm = gsap.matchMedia();

    // add a media query. When it matches, the associated function will run
    mm.add("(max-width: 479px)", () => {

      gsap.to(".grid_thirds_2", {
        y: 600,
        duration: 2,
        ease: 'none',
        scrollTrigger: {
          start: "+=1400",
          // trigger: ".grid_thirds_1",
          toggleActions: "restart pause reverse pause",
          end: 'bottom',
          scrub: 1,
        }
      }
      );

      gsap.to(".grid_thirds_1", {
        y: -600,
        duration: 2,
        ease: 'none',
        scrollTrigger: {
          start: "+=1400",
          // trigger: ".grid_thirds_1",
          toggleActions: "restart pause reverse pause",
          end: 'bottom',
          scrub: 1,
        }
      }
      );

      return () => { // optional
        // custom cleanup code here (runs when it STOPS matching)
      };
    });


  }, []);

  useEffect(() => {
    // define a custom handler function
    // for the contextmenu event
    const handleContextMenu = (e) => {
      // prevent the right-click menu from appearing
      e.preventDefault()
    }

    // attach the event listener to 
    // the document object
    document.addEventListener("contextmenu", handleContextMenu)

    // clean up the event listener when 
    // the component unmounts
    return () => {
      document.removeEventListener("contextmenu", handleContextMenu)
    }
  }, [])

  return (
    <>
      <Head>
        <title>BRIELLA GARCCIA</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      {/* Fisrt Section */}
      <div className={style.hero_first}>
        <div className={style.container}>
          <div className={style.flex_hero}>
            <h1 className={style.hero_title}>
              Briella Garcia<br />
              <span className={style.biger_font}>&amp;</span>
              sus increibles<br /> Quince Años.
            </h1>
            <Image
              src={home_1}
              loading="lazy"
              width={600}
              sizes="(max-width: 991px) 72vw, 600px"
              alt=""
              className={`${style.hero_image} ${style.image_about}`}
            />
            <div className={style.absolute_line}>
              <Image
                src={blob}
                loading="lazy"
                width="75.5"
                alt=""
                className={style.blog_image}
              />
            </div>
          </div>
        </div>
      </div>

      {/* Frase */}
      <div className={style.section}>
        <div className={style.container}>
          <div
            className={style.max_w_about}
          >
            <div className={style.top_small_text}>Briella Garccia</div>
            <div>
              <h2>
                La vida es como una cámara, enfócate solo en lo importante, captura los buenos momentos, saca de lo
                negativo algo positivo y si no sale como esperabas, intenta una nueva toma.
              </h2>
            </div>
            <div className={style.margin_30px}>
              <Link href="/About" className={`${style.nav_link} ${style.full} ${style.w_inline_block}`}>
                <div>Ver Más</div>
              </Link>
            </div>
          </div>
        </div>
      </div>

      {/* Categorys */}
      <div className="category">
        <div className={style.w_dyn_list}>
          <div className={style.w_dyn_items}>
            <div className={`${style.move} ${style.w_dyn_item}`}>
              <div className={style.grid_2_columns}>
                <div
                  id={style["w-node-_06ae92da-d4a8-172b-1b65-3216431bf40c-75fd0c8e"]}
                  className={style.treatment_content}
                >
                  <div className={style.service_content}>
                    <h2 className={style.service_title}>Sesión de Fotos</h2>
                    <div className={style.margin_15px}>
                      <p>
                        Nadie nos pertenece, excepto los recuerdos.
                      </p>
                    </div>
                    <div className={style.margin_40px}>
                      <Link
                        href="/Portfolio"
                        className={`${style.nav_link} ${style.full} ${style.w_inline_block}`}
                      >
                        <div>Ver Más</div>
                      </Link>
                    </div>
                  </div>
                </div>
                <Image
                  id={style["w-node-_821bc079-45fa-d4a6-98d6-70d472ce63a8-75fd0c8e"]}
                  src={home_2}
                  className={`${style.treatment_photo} ${style.image_about}`}
                  alt=''
                />
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="category">
        <div className="w-dyn-list">
          <div className="w-dyn-items">
            <div className={`${style.move} ${style.w_dyn_item}`}>
              <div className={`${style.grid_2_columns} ${style.reverse}`}>
                <Image
                  id={style["w-node-_2a3250f8-6f49-4faa-22be-322c23cc58bc-75fd0c8e"]}
                  src={home_3}
                  className={`${style.treatment_photo} ${style.image_about}`}
                  alt=''
                />
                <div
                  id={style["w-node-_2a3250f8-6f49-4faa-22be-322c23cc58b3-75fd0c8e"]}
                  className={style.treatment_content}
                >
                  <div className={style.service_content}>
                    <h2 className={style.service_title}>Ceremonia</h2>
                    <div className={style.margin_15px}>
                      <p>
                        No necesito filtros.
                      </p>
                    </div>
                    <div className={style.margin_40px}>
                      <Link
                        href="/Portfolio"
                        className={`${style.nav_link} ${style.full} ${style.w_inline_block}`}
                      >
                        <div>Ver Más</div>
                      </Link>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Gallery */}
      <div className={`${style.section} ${style.instagram}`}>
        <div>
          <div className={`${style.max_w_about} ${style.first}`}>
            <div className={style.top_small_text}>BRIELLA GARCCIA</div>
            <div className={style.margin_20px}>
              <h2 className={style.title_2}>
                <Link
                  href="/Portfolio"
                  target="_blank"
                  className={style.instagram_link}
                >
                  Gallery
                </Link>
              </h2>
              <div className={style.margin_30px}>
                <Link href="/Portfolio" className={`${style.nav_link} ${style.full} ${style.w_inline_block}`}>
                  <div>Ver</div>
                </Link>
              </div>
            </div>
          </div>
        </div>
        <div
          className={`${style.instagram_column} ${style.left} grid_thirds_1`}
          style={{
            willChange: "transform",
            transform:
              "translate3d(0px, -74.624px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)",
            transformStyle: "preserve-3d"
          }}
        >
          <Image
            src={gallery_1}
            loading="eager"
            sizes="(max-width: 479px) 90px, (max-width: 767px) 140px, (max-width: 991px) 180px, 280px"
            alt=""
            className={style.image_about}
          />
          <Image
            src={gallery_2}
            loading="eager"
            sizes="(max-width: 479px) 90px, (max-width: 767px) 140px, (max-width: 991px) 180px, 280px"
            alt=""
          />
          <Image
            src={gallery_3}
            loading="eager"
            sizes="(max-width: 479px) 90px, (max-width: 767px) 140px, (max-width: 991px) 180px, 280px"
            alt=""
          />
        </div>
        <div
          className={`${style.instagram_column} ${style.right} grid_thirds_2`}
          style={{
            willChange: "transform",
            transform:
              "translate3d(0px, -127.624px, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)",
            transformStyle: "preserve-3d"
          }}
        >
          <Image
            src={gallery_4}
            loading="eager"
            sizes="(max-width: 479px) 90px, (max-width: 767px) 140px, (max-width: 991px) 180px, 280px"
            alt=""
          />
          <Image
            src={gallery_5}
            loading="eager"
            sizes="(max-width: 479px) 90px, (max-width: 767px) 140px, (max-width: 991px) 180px, 280px"
            alt=""
          />
          <Image
            src={gallery_6}
            loading="eager"
            sizes="(max-width: 479px) 90px, (max-width: 767px) 140px, (max-width: 991px) 180px, 280px"
            alt=""
          />
        </div>
      </div>

      {/* Testimonials */}
      <div className={`${style.section} ${style.red}`}>

        <div className={style.container}>

          <Swiper
            slidesPerView={1}
            spaceBetween={30}
            loop={true}
            pagination={{
              clickable: true,
            }}
            autoplay={{
              delay: 2500,
              disableOnInteraction: false,
            }}
            effect={"creative"}
            creativeEffect={{
              prev: {
                // shadow: true,
                translate: ["-120%", 0, -500],
              },
              next: {
                // shadow: true,
                translate: ["120%", 0, -500],
              },
            }}
            // navigation={true}
            modules={[Pagination, Navigation, Autoplay, EffectCreative]}
            className="mySwiper"
          >
            <SwiperSlide>

              <div className={style.qoute_wrapper}>
                <div className={style.qoute_content}>
                  <Image
                    src={mark_testi}
                    loading="lazy"
                    width={70}
                    alt=""
                    className={style.qoute_image}
                  />
                  <h2 className={style.qoute_text}>
                  &quot;¡Feliz 15 años! La vida está empezando para ti. Deseo que la disfrutes
                    mucho y que la alegría y el amor hagan siempre parte de tu camino.&quot;
                  </h2>
                </div>
                <div className={style.flex_space_between}>
                  <div className={`${style.top_small_text} ${style.lighter}`}>
                    Robert Martini
                  </div>
                </div>
              </div>


            </SwiperSlide>
            <SwiperSlide>
              <div className={style.qoute_wrapper}>
                <div className={style.qoute_content}>
                  <Image
                    src={mark_testi}
                    loading="lazy"
                    width={70}
                    alt=""
                    className={style.qoute_image}
                  />
                  <h2 className={style.qoute_text}>
                  &quot;Con los 15 años, nuevas aventuras llegarán a tu vida, ¡disfrútalas y aprende de ellas! ¡Muchas felicidades!&quot;
                  </h2>
                </div>
                <div className={style.flex_space_between}>
                  <div className={`${style.top_small_text} ${style.lighter}`}>
                    Julian Rivalto
                  </div>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className={style.qoute_wrapper}>
                <div className={style.qoute_content}>
                  <Image
                    src={mark_testi}
                    loading="lazy"
                    width={70}
                    alt=""
                    className={style.qoute_image}
                  />
                  <h2 className={style.qoute_text}>
                  &quot;Un día como hoy nació una flor como tú, espero estos 15 años sean fabulosos y dignos de una princesa. ¡Feliz cumpleaños!&quot;
                  </h2>
                </div>
                <div className={style.flex_space_between}>
                  <div className={`${style.top_small_text} ${style.lighter}`}>
                    Logan Peréz
                  </div>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className={style.qoute_wrapper}>
                <div className={style.qoute_content}>
                  <Image
                    src={mark_testi}
                    loading="lazy"
                    width={70}
                    alt=""
                    className={style.qoute_image}
                  />
                  <h2 className={style.qoute_text}>
                  &quot;Querida quinceañera, hoy tienes una fiesta de celebración, y parece que el regalo lo recibí yo al ver tan hermosa sonrisa en tu rostro. ¡Feliz cumpleaños!&quot;
                  </h2>
                </div>
                <div className={style.flex_space_between}>
                  <div className={`${style.top_small_text} ${style.lighter}`}>
                    Fiorella Martini
                  </div>
                </div>
              </div>
            </SwiperSlide>
          </Swiper>

        </div>

      </div >

      {/* Ella */}
      <div div className={style.section} >
        <div className={style.container}>
          <div className={style.services_grid}>
            <div
              id={style["w-node-a2359bc5-54f1-908c-92cc-a476cc8f4a82-ccd4aa67"]}
              className={style.services_grid_column_1}
            >
              <h2 className={style.display_2}>
                Festividad de <span className={style.bold_italic_text}>Briella</span> con sus más allegados.
              </h2>
              <div className={style.paragraph_large}>
                I love shooting <span className={style.bold_italic_text}>weddings</span>{" "}
                &amp; <span className={style.bold_italic_text}>couples</span>
                <span className={style.bold_italic_text} /> since there are so many feelings
                Lorem Ipsum is simply dummy text of the printing and typesetting
                industry. Lorem Ipsum has been the industry&apos;s standard dummy
              </div>
              <Image
                src={home_5}
                loading="lazy"
                width={825}
                alt="Bride and groom - Blume Photography Webflow Template"
                className={`${style.services_image_big} ${style.image_home}`}
              />
              <Image
                src={text}
                loading="lazy"
                style={{ opacity: 1 }}
                alt=""
                className={style.services_blume}
              />
              <Image
                src={shape2}
                loading="lazy"
                style={{ opacity: 1 }}
                alt=""
                className={style.services_shape}
              />
            </div>
            <div
              id={style["w-node-_78efd06d-c1e1-df60-db23-373d909b8ea5-ccd4aa67"]}
              className={style.services_grid_column_2}
            >
              <Image
                src={home_4}
                loading="lazy"
                width={383}
                height={575}
                alt="Couple - Blume Photography Webflow Template"
                className={`${style.services_image_small} ${style.image_home}`}
              />
              <p className={style.paragraph_large}>
                Lorem Ipsum is simply dummy text of the printing and typesetting
                industry. Lorem Ipsum has been the industry&apos;s standard dummy
                Lorem Ipsum is simply dummy text of the printing and typesetting
                industry. Lorem Ipsum has been the industry&apos;s standard dummy
              </p>
            </div>
          </div>
        </div>
      </div >


      <Footer />


    </ >
  )
}
