import Head from 'next/head'
import React from 'react'
import Image from 'next/image'
import Link from 'next/link'

import style from '@/styles/Home.module.css'

// Images
import p1_1000x625 from '../public/images/Portfolio/p1_1000x625.jpg'
import p2_1000x1490 from '../public/images/Portfolio/p2_1000x1490.jpg'
import content_folio from '../public/images/Portfolio/content_folio.png'
import p3_1304x794 from '../public/images/Portfolio/p3_1304x794.jpg'
import design_icon from '../public/images/Portfolio/design-icon.svg'
import Footer from './components/Footer'


export default function Portfolio() {
    return (
        <>

            <Head>
                <title>Portafolio</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {/* Title */}
            <div className={`${style.top_section} ${style.pd_bottom_180px}`}>
                <div className={`${style.container_default} ${style.position_relative___z_index_1} ${style.w_container}`}>
                    <div className={`${style.text_center} ${style.mg_bottom_56px}`}>
                        <div className={`${style.inner_container} ${style._856px} ${style.center}`}>
                            <h1 className={`${style.display_1} ${style.mg_bottom_8px} ${style.about_title}`}>
                                Titulo &amp; Titulo
                            </h1>
                            <p
                                style={{
                                    transform:
                                        "translate3d(0px, 0%, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)",
                                    transformStyle: "preserve-3d",
                                    opacity: 1
                                }}
                                className={style.mg_bottom_0}
                            >
                                Dolor non massa ac rhoncus diam turpis consequat, vitae velit orci nec
                                sit ut faucibus tristique facilisi accumsan proin dignissim
                                condimentum imperdiet scelerisque dictum.
                            </p>
                        </div>
                    </div>
                    <div className="bg-dot top-section-3-cards---top-dot" />
                    <div className="bg-dot top-section-3-cards---middle-left-dot" />
                    <div className="bg-dot top-section-3-cards---middle-right-dot" />
                    <div className="bg-dot top-section-3-cards---bottom-right-dot" />
                </div>
                <div className={`${style.bg_secondary_5} ${style.bottom_30}`} />
            </div>


            {/* Content Image */}
            <div className="wf-section">
                <div className={`${style.container_default} ${style.w_container}`}>
                    <div
                        style={{ opacity: 1 }}
                        className={`${style.card} ${style.newsletter_card}`}
                    >
                        <Image
                            src={content_folio}
                            width={494}
                            height={534}
                            loading="eager"
                            style={{
                                transform:
                                    "translate3d(0px, 0%, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)",
                                transformStyle: "preserve-3d",
                                opacity: 1
                            }}
                            alt="Subscribe To Our Newsletter - eLearner X Webflow Template"
                            className={`${style.port_swadow} ${style.image_home}`}
                        />
                        <div
                            id={style["w-node-e658d80e-3055-6413-e9d0-9cf6fed2f3ce-8f1120fd"]}
                            style={{
                                transform:
                                    "translate3d(0px, 0%, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)",
                                transformStyle: "preserve-3d",
                                opacity: 1
                            }}
                        >
                            <h2 className={`${style.display_3} ${style.color_neutral_100} ${style.mg_bottom_24px}`}>
                                Titulo &amp; Titulo
                            </h2>
                            <p className={style.mg_bottom_32px}>
                                Non magna tempor sit at donec cursus adipiscing adipis ut at pharetra
                                habitant sagittis tincidunt adipiscing gravida.
                            </p>
                        </div>
                    </div>
                </div>
            </div>


            {/* Gallery */}
            <div id={style['Gallery']} className={`${style.section_gal} wf-section`}>
                <div className={`${style.container_default} ${style.w_container}`}>
                    <div className={"w_dyn_list"}>
                        <div role="list" className={`${style.grid_2_columns} w_dyn_items`}>

                            {/* ======== */}
                            <div
                                id={style["w-node-_8eac74c1-58f5-9f76-046b-f900c7edd46e-8f1120fd"]}
                                style={{
                                    transform:
                                        "translate3d(0px, 0%, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)",
                                    transformStyle: "preserve-3d",
                                    opacity: 1
                                }}
                                role="listitem"
                                className="w-dyn-item"
                            >
                                <Link
                                    href="/"
                                    className={`${style.card} ${style.card_link_image_top} ${style.hover_transform_1_01} ${style.w_inline_block}`}
                                >
                                    <div className={style.link_item___image_wrapper}>
                                        <Image
                                            src={p2_1000x1490}
                                            width={600}
                                            loading="eager"
                                            alt="How to design a simple, yet unique and memorable brand identity"
                                            sizes="(max-width: 479px) 93vw, (max-width: 767px) 95vw, (max-width: 1439px) 46vw, 608px"
                                            className={style.link_item___image}
                                        />
                                        <div className={style.badge_wrapper_top_right}>
                                            <div className={`${style.badge_secondary} ${style.small}`}>
                                                <div className={`${style.flex} ${style.align_center} ${style.gap_column_12px}`}>
                                                    <Image
                                                        src={design_icon}
                                                        loading="eager"
                                                        alt="How to design a simple, yet unique and memorable brand identity"
                                                    />
                                                    <div>Titulo</div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </Link>
                            </div>
                            {/* ======== */}
                            <div
                                id={style["w-node-_8eac74c1-58f5-9f76-046b-f900c7edd46e-8f1120fd"]}
                                style={{
                                    transform:
                                        "translate3d(0px, 0%, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)",
                                    transformStyle: "preserve-3d",
                                    opacity: 1
                                }}
                                className={style.w_dyn_item}
                            >
                                <Link
                                    href="/"
                                    className={`${style.card} ${style.card_link_image_top} ${style.hover_transform_1_01} ${style.w_inline_block}`}
                                >
                                    <div className={style.link_item___image_wrapper}>
                                        <Image
                                            src={p3_1304x794}
                                            width={1304}
                                            height={794}
                                            loading="eager"
                                            alt="How to design a simple, yet unique and memorable brand identity"
                                            sizes="(max-width: 479px) 93vw, (max-width: 767px) 95vw, (max-width: 1439px) 46vw, 608px"
                                            className={style.link_item___image}
                                        />
                                        <div className={style.badge_wrapper_top_right}>
                                            <div className={`${style.badge_secondary} ${style.small}`}>
                                                <div className={`${style.flex} ${style.align_center} ${style.gap_column_12px}`}>
                                                    <Image
                                                        src={design_icon}
                                                        loading="eager"
                                                        alt="How to design a simple, yet unique and memorable brand identity"
                                                    />
                                                    <div>Titulo</div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </Link>
                            </div>
                            <div
                                id={style["w-node-_8eac74c1-58f5-9f76-046b-f900c7edd46e-8f1120fd"]}
                                style={{
                                    transform:
                                        "translate3d(0px, 0%, 0px) scale3d(1, 1, 1) rotateX(0deg) rotateY(0deg) rotateZ(0deg) skew(0deg, 0deg)",
                                    transformStyle: "preserve-3d",
                                    opacity: 1
                                }}
                                className={style.w_dyn_item}
                            >
                                <Link
                                    href="/"
                                    className={`${style.card} ${style.card_link_image_top} ${style.hover_transform_1_01} ${style.w_inline_block}`}
                                >
                                    <div className={style.link_item___image_wrapper}>
                                        <Image
                                            src={p1_1000x625}
                                            loading="eager"
                                            alt="How to design a simple, yet unique and memorable brand identity"
                                            sizes="(max-width: 479px) 93vw, (max-width: 767px) 95vw, (max-width: 1439px) 46vw, 608px"
                                            className={style.link_item___image}
                                        />
                                        <div className={style.badge_wrapper_top_right}>
                                            <div className={`${style.badge_secondary} ${style.small}`}>
                                                <div className={`${style.flex} ${style.align_center} ${style.gap_column_12px}`}>
                                                    <Image
                                                        src={design_icon}
                                                        loading="eager"
                                                        alt="How to design a simple, yet unique and memorable brand identity"
                                                    />
                                                    <div>Titulo</div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </Link>
                            </div>


                        </div>
                    </div>
                </div>
            </div>


            <Footer />

        </>
    )
}
